title: "Ubong Etok Portfolio"
description: "Professional portfolio of Ubong Etok – Business Intelligence Manager, Data Scientist, and Analyst."
baseurl: ""
url: "https://xzibitetok.github.io"

# Build settings
theme: minima
plugins:
  - jekyll-feed
