title: "Ubong Etok Portfolio"
description: "Professional portfolio of Ubong Etok — Data Scientist, Analyst, and BI Enthusiast"
baseurl: "" 
url: "https://xzibitetok.github.io"

# Build settings
markdown: kramdown
theme: minima

# Navigation
nav:
  - name: "About"
    link: "#about"
  - name: "Resume"
    link: "#resume"
  - name: "Achievements"
    link: "#achievements"
  - name: "Services"
    link: "#services"
  - name: "Projects"
    link: "#projects"
  - name: "Contact"
    link: "#contact"
