title: "Xzibitetok's GitHub Profile"
author: "Ubong Etok"

navbar-links:
  Home: "home"
  About: "about"
  Services: "services"
  Projects: "projects"
  Contact: "contact"

avatar: "/assets/img/githubpics.jpg"
round-avatar: true
favicon: "/assets/img/favicon.ico"

social-network-links:
  email: ubyetok@gmail.com
  github: xzibitetok
  linkedin: ubong-etok-56b4a0170
  facebook: uby.etok.5
  whatsapp: +2348161777214

site-css:
  - "/assets/css/custom-styles.css"

timezone: "Africa/Lagos"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/

plugins:
  - jekyll-paginate
  - jekyll-sitemap
