# Site settings
title: "Ubong Etok Portfolio"
email: "ubyetok@gmail.com"
description: "Business Intelligence Manager & Data Scientist Portfolio"
baseurl: "" # leave blank for GitHub Pages
url: "https://xzibitetok.github.io"

# Author info
author:
  name: "Ubong Etok"
  email: "ubyetok@gmail.com"

# Theme settings (if using Beautiful Jekyll)
theme: "beautiful-jekyll"

# Social network links
social-network-links:
  whatsapp: "+2348161777214"
  linkedin: "ubong-etok-56b4a0170"
  facebook: "uby.etok.5"
  email: "ubyetok@gmail.com"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
