title: "Ubong Etok"
description: "Data Scientist | Business Intelligence Manager | Portfolio"
baseurl: ""
url: "https://xzibitetok.github.io"

# Navigation
nav_links:
  - name: "About"
    url: "#about"
  - name: "Resume"
    url: "#resume"
  - name: "Achievements"
    url: "#achievements"
  - name: "Services"
    url: "#services"
  - name: "Projects"
    url: "#projects"
  - name: "Contact"
    url: "#contact"

# Build settings
theme: minima
plugins:
  - jekyll-feed
